// Generated by delombok at Thu Jun 14 14:59:06 CEST 2018
package com.remondis.remap.demo;

public class Person {
  private String salutation;
  private String forname;
  private String name;
  private Gender gender;
  private double bodyHeight;


  @java.lang.SuppressWarnings("all")
  public static class PersonBuilder {
    @java.lang.SuppressWarnings("all")
    private String salutation;
    @java.lang.SuppressWarnings("all")
    private String forname;
    @java.lang.SuppressWarnings("all")
    private String name;
    @java.lang.SuppressWarnings("all")
    private Gender gender;
    @java.lang.SuppressWarnings("all")
    private double bodyHeight;

    @java.lang.SuppressWarnings("all")
    PersonBuilder() {
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder salutation(final String salutation) {
      this.salutation = salutation;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder forname(final String forname) {
      this.forname = forname;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder name(final String name) {
      this.name = name;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder gender(final Gender gender) {
      this.gender = gender;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder bodyHeight(final double bodyHeight) {
      this.bodyHeight = bodyHeight;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public Person build() {
      return new Person(salutation, forname, name, gender, bodyHeight);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
      return "Person.PersonBuilder(salutation=" + this.salutation + ", forname=" + this.forname + ", name=" + this.name + ", gender=" + this.gender + ", bodyHeight=" + this.bodyHeight + ")";
    }
  }

  @java.lang.SuppressWarnings("all")
  public static PersonBuilder builder() {
    return new PersonBuilder();
  }

  @java.lang.SuppressWarnings("all")
  public Person() {
  }

  @java.lang.SuppressWarnings("all")
  public Person(final String salutation, final String forname, final String name, final Gender gender, final double bodyHeight) {
    this.salutation = salutation;
    this.forname = forname;
    this.name = name;
    this.gender = gender;
    this.bodyHeight = bodyHeight;
  }

  @java.lang.SuppressWarnings("all")
  public String getSalutation() {
    return this.salutation;
  }

  @java.lang.SuppressWarnings("all")
  public String getForname() {
    return this.forname;
  }

  @java.lang.SuppressWarnings("all")
  public String getName() {
    return this.name;
  }

  @java.lang.SuppressWarnings("all")
  public Gender getGender() {
    return this.gender;
  }

  @java.lang.SuppressWarnings("all")
  public double getBodyHeight() {
    return this.bodyHeight;
  }

  @java.lang.SuppressWarnings("all")
  public void setSalutation(final String salutation) {
    this.salutation = salutation;
  }

  @java.lang.SuppressWarnings("all")
  public void setForname(final String forname) {
    this.forname = forname;
  }

  @java.lang.SuppressWarnings("all")
  public void setName(final String name) {
    this.name = name;
  }

  @java.lang.SuppressWarnings("all")
  public void setGender(final Gender gender) {
    this.gender = gender;
  }

  @java.lang.SuppressWarnings("all")
  public void setBodyHeight(final double bodyHeight) {
    this.bodyHeight = bodyHeight;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Person)) return false;
    final Person other = (Person) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$salutation = this.getSalutation();
    final java.lang.Object other$salutation = other.getSalutation();
    if (this$salutation == null ? other$salutation != null : !this$salutation.equals(other$salutation)) return false;
    final java.lang.Object this$forname = this.getForname();
    final java.lang.Object other$forname = other.getForname();
    if (this$forname == null ? other$forname != null : !this$forname.equals(other$forname)) return false;
    final java.lang.Object this$name = this.getName();
    final java.lang.Object other$name = other.getName();
    if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
    final java.lang.Object this$gender = this.getGender();
    final java.lang.Object other$gender = other.getGender();
    if (this$gender == null ? other$gender != null : !this$gender.equals(other$gender)) return false;
    if (java.lang.Double.compare(this.getBodyHeight(), other.getBodyHeight()) != 0) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Person;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $salutation = this.getSalutation();
    result = result * PRIME + ($salutation == null ? 43 : $salutation.hashCode());
    final java.lang.Object $forname = this.getForname();
    result = result * PRIME + ($forname == null ? 43 : $forname.hashCode());
    final java.lang.Object $name = this.getName();
    result = result * PRIME + ($name == null ? 43 : $name.hashCode());
    final java.lang.Object $gender = this.getGender();
    result = result * PRIME + ($gender == null ? 43 : $gender.hashCode());
    final long $bodyHeight = java.lang.Double.doubleToLongBits(this.getBodyHeight());
    result = result * PRIME + (int) ($bodyHeight >>> 32 ^ $bodyHeight);
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Person(salutation=" + this.getSalutation() + ", forname=" + this.getForname() + ", name=" + this.getName() + ", gender=" + this.getGender() + ", bodyHeight=" + this.getBodyHeight() + ")";
  }
}
