// Generated by delombok at Thu Jun 14 14:59:06 CEST 2018
package com.remondis.remap.mapInto;

public class AddressLite {
  private String street;
  private String city;


  @java.lang.SuppressWarnings("all")
  public static class AddressLiteBuilder {
    @java.lang.SuppressWarnings("all")
    private String street;
    @java.lang.SuppressWarnings("all")
    private String city;

    @java.lang.SuppressWarnings("all")
    AddressLiteBuilder() {
    }

    @java.lang.SuppressWarnings("all")
    public AddressLiteBuilder street(final String street) {
      this.street = street;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public AddressLiteBuilder city(final String city) {
      this.city = city;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public AddressLite build() {
      return new AddressLite(street, city);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
      return "AddressLite.AddressLiteBuilder(street=" + this.street + ", city=" + this.city + ")";
    }
  }

  @java.lang.SuppressWarnings("all")
  public static AddressLiteBuilder builder() {
    return new AddressLiteBuilder();
  }

  @java.lang.SuppressWarnings("all")
  public AddressLite() {
  }

  @java.lang.SuppressWarnings("all")
  public AddressLite(final String street, final String city) {
    this.street = street;
    this.city = city;
  }

  @java.lang.SuppressWarnings("all")
  public String getStreet() {
    return this.street;
  }

  @java.lang.SuppressWarnings("all")
  public String getCity() {
    return this.city;
  }

  @java.lang.SuppressWarnings("all")
  public void setStreet(final String street) {
    this.street = street;
  }

  @java.lang.SuppressWarnings("all")
  public void setCity(final String city) {
    this.city = city;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof AddressLite)) return false;
    final AddressLite other = (AddressLite) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$street = this.getStreet();
    final java.lang.Object other$street = other.getStreet();
    if (this$street == null ? other$street != null : !this$street.equals(other$street)) return false;
    final java.lang.Object this$city = this.getCity();
    final java.lang.Object other$city = other.getCity();
    if (this$city == null ? other$city != null : !this$city.equals(other$city)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof AddressLite;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $street = this.getStreet();
    result = result * PRIME + ($street == null ? 43 : $street.hashCode());
    final java.lang.Object $city = this.getCity();
    result = result * PRIME + ($city == null ? 43 : $city.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "AddressLite(street=" + this.getStreet() + ", city=" + this.getCity() + ")";
  }
}
