// Generated by delombok at Thu Jun 14 14:59:06 CEST 2018
package com.remondis.remap.mapInto;

import java.util.List;

public class Person {
  private Integer age;
  private String forename;
  private String lastname;
  private List<Address> addresses;


  @java.lang.SuppressWarnings("all")
  public static class PersonBuilder {
    @java.lang.SuppressWarnings("all")
    private Integer age;
    @java.lang.SuppressWarnings("all")
    private String forename;
    @java.lang.SuppressWarnings("all")
    private String lastname;
    @java.lang.SuppressWarnings("all")
    private List<Address> addresses;

    @java.lang.SuppressWarnings("all")
    PersonBuilder() {
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder age(final Integer age) {
      this.age = age;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder forename(final String forename) {
      this.forename = forename;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder lastname(final String lastname) {
      this.lastname = lastname;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public PersonBuilder addresses(final List<Address> addresses) {
      this.addresses = addresses;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public Person build() {
      return new Person(age, forename, lastname, addresses);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
      return "Person.PersonBuilder(age=" + this.age + ", forename=" + this.forename + ", lastname=" + this.lastname + ", addresses=" + this.addresses + ")";
    }
  }

  @java.lang.SuppressWarnings("all")
  public static PersonBuilder builder() {
    return new PersonBuilder();
  }

  @java.lang.SuppressWarnings("all")
  public Person() {
  }

  @java.lang.SuppressWarnings("all")
  public Person(final Integer age, final String forename, final String lastname, final List<Address> addresses) {
    this.age = age;
    this.forename = forename;
    this.lastname = lastname;
    this.addresses = addresses;
  }

  @java.lang.SuppressWarnings("all")
  public Integer getAge() {
    return this.age;
  }

  @java.lang.SuppressWarnings("all")
  public String getForename() {
    return this.forename;
  }

  @java.lang.SuppressWarnings("all")
  public String getLastname() {
    return this.lastname;
  }

  @java.lang.SuppressWarnings("all")
  public List<Address> getAddresses() {
    return this.addresses;
  }

  @java.lang.SuppressWarnings("all")
  public void setAge(final Integer age) {
    this.age = age;
  }

  @java.lang.SuppressWarnings("all")
  public void setForename(final String forename) {
    this.forename = forename;
  }

  @java.lang.SuppressWarnings("all")
  public void setLastname(final String lastname) {
    this.lastname = lastname;
  }

  @java.lang.SuppressWarnings("all")
  public void setAddresses(final List<Address> addresses) {
    this.addresses = addresses;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Person)) return false;
    final Person other = (Person) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$age = this.getAge();
    final java.lang.Object other$age = other.getAge();
    if (this$age == null ? other$age != null : !this$age.equals(other$age)) return false;
    final java.lang.Object this$forename = this.getForename();
    final java.lang.Object other$forename = other.getForename();
    if (this$forename == null ? other$forename != null : !this$forename.equals(other$forename)) return false;
    final java.lang.Object this$lastname = this.getLastname();
    final java.lang.Object other$lastname = other.getLastname();
    if (this$lastname == null ? other$lastname != null : !this$lastname.equals(other$lastname)) return false;
    final java.lang.Object this$addresses = this.getAddresses();
    final java.lang.Object other$addresses = other.getAddresses();
    if (this$addresses == null ? other$addresses != null : !this$addresses.equals(other$addresses)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Person;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $age = this.getAge();
    result = result * PRIME + ($age == null ? 43 : $age.hashCode());
    final java.lang.Object $forename = this.getForename();
    result = result * PRIME + ($forename == null ? 43 : $forename.hashCode());
    final java.lang.Object $lastname = this.getLastname();
    result = result * PRIME + ($lastname == null ? 43 : $lastname.hashCode());
    final java.lang.Object $addresses = this.getAddresses();
    result = result * PRIME + ($addresses == null ? 43 : $addresses.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Person(age=" + this.getAge() + ", forename=" + this.getForename() + ", lastname=" + this.getLastname() + ", addresses=" + this.getAddresses() + ")";
  }
}
