// Generated by delombok at Thu Jun 14 14:59:06 CEST 2018
package com.remondis.remap.flatCollectionMapping;

import java.util.List;

public class Destination {
  private List<Id> ids;


  @java.lang.SuppressWarnings("all")
  public static class DestinationBuilder {
    @java.lang.SuppressWarnings("all")
    private List<Id> ids;

    @java.lang.SuppressWarnings("all")
    DestinationBuilder() {
    }

    @java.lang.SuppressWarnings("all")
    public DestinationBuilder ids(final List<Id> ids) {
      this.ids = ids;
      return this;
    }

    @java.lang.SuppressWarnings("all")
    public Destination build() {
      return new Destination(ids);
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
      return "Destination.DestinationBuilder(ids=" + this.ids + ")";
    }
  }

  @java.lang.SuppressWarnings("all")
  public static DestinationBuilder builder() {
    return new DestinationBuilder();
  }

  @java.lang.SuppressWarnings("all")
  public List<Id> getIds() {
    return this.ids;
  }

  @java.lang.SuppressWarnings("all")
  public void setIds(final List<Id> ids) {
    this.ids = ids;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Destination)) return false;
    final Destination other = (Destination) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$ids = this.getIds();
    final java.lang.Object other$ids = other.getIds();
    if (this$ids == null ? other$ids != null : !this$ids.equals(other$ids)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Destination;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $ids = this.getIds();
    result = result * PRIME + ($ids == null ? 43 : $ids.hashCode());
    return result;
  }

  @java.lang.SuppressWarnings("all")
  public Destination() {
  }

  @java.lang.SuppressWarnings("all")
  public Destination(final List<Id> ids) {
    this.ids = ids;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Destination(ids=" + this.getIds() + ")";
  }
}
